[Desktop Entry]
Name=Discover
Name[ar]=المستكشف
Name[ast]=Discover
Name[az]=Discover
Name[be]=Discover
Name[bg]=Discover
Name[ca]=Discover
Name[ca@valencia]=Discover
Name[cs]=Discover
Name[da]=Discover
Name[de]=Discover
Name[el]=Discover
Name[en_GB]=Discover
Name[eo]=Discover
Name[es]=Discover
Name[et]=Discover
Name[eu]=Discover
Name[fa]=فروشگاه نرم‌افزار
Name[fi]=Discover
Name[fr]=Discover
Name[gl]=Descubrir
Name[he]=Discover
Name[hi]=डिस्कवर
Name[hu]=Discover
Name[ia]=Discover (Discoperi)
Name[id]=Discover
Name[ie]=Discover
Name[is]=Discover
Name[it]=Discover
Name[ja]=Discover
Name[ka]=Discover
Name[ko]=Discover
Name[lt]=Discover
Name[lv]=Discover
Name[ml]=കണ്ടെത്തുക
Name[my]=ဒစ်(စ)ကာဗာ
Name[nb]=Discover
Name[nl]=Ontdekken
Name[nn]=Discover
Name[pa]=ਡਿਸਕਵਰ
Name[pl]=Discover
Name[pt]=Discover
Name[pt_BR]=Discover
Name[ro]=Discover
Name[ru]=Discover
Name[sa]=डिस्कवर्
Name[sk]=Discover
Name[sl]=Discover
Name[sr]=Oткривач
Name[sr@ijekavian]=Oткривач
Name[sr@ijekavianlatin]=Otkrivač
Name[sr@latin]=Otkrivač
Name[sv]=Upptäck
Name[ta]=டிஸ்கவர்
Name[tg]=Кашфиёт
Name[tr]=Keşfet
Name[uk]=Discover
Name[zh_CN]=Discover 软件中心
Name[zh_TW]=Discover
Comment=Install and remove apps and add-ons
Comment[ar]=ثبت وأزل الحزم والملحقات
Comment[bg]=Инсталиране и премахване на приложения и приставки
Comment[ca]=Instal·la i elimina aplicacions i complements
Comment[ca@valencia]=Instal·la i elimina aplicacions i complements
Comment[cs]=Instaluje a odebírá aplikace či doplňky
Comment[de]=Anwendungen und Erweiterungen installieren und entfernen
Comment[eo]=Instali kaj forigi apojn kaj kromaĵojn
Comment[es]=Instalar y eliminar aplicaciones y complementos
Comment[eu]=Aplikazioak eta gehigarriak instalatzea eta kentzea
Comment[fa]=نصب و پاک کردن برنامه‌ها و افزونه‌ها
Comment[fi]=Asenna ja poista sovelluksia ja lisäosia
Comment[fr]=Installer et supprimer des applications et des modules complémentaires
Comment[gl]=Instalar e desinstalar aplicacións e complementos.
Comment[he]=הוספת והסרת יישומים ותוספים
Comment[hu]=Alkalmazások és bővítmények telepítése és eltávolítása
Comment[ia]=Installa e remove apps e add-ons
Comment[is]=Setja upp og fjarlægja forrit og viðbætur
Comment[it]=Installa e rimuovi applicazioni e componenti aggiuntivi
Comment[ja]=アプリケーションやアドオンをインストールまたは削除
Comment[ka]=დააყენეთ და წაშალეთ აპები და დამატებები
Comment[ko]=앱과 추가 기능 설치 및 삭제
Comment[lt]=Įdiegti ir šalinti programas bei papildinius
Comment[lv]=Instalējiet un noņemiet programmas un pielikumus
Comment[nl]=Installeer en verwijder toepassingen en add-ons
Comment[nn]=Installer og fjern program og programtillegg
Comment[pl]=Wgrywaj i usuwaj aplikacje oraz dodatki do nich
Comment[pt]=Instalar e remover aplicações e extensões
Comment[pt_BR]=Instalar e remover programas e complementos
Comment[ro]=Instalează și elimină aplicații și suplimente
Comment[ru]=Установка и удаление приложений и дополнений
Comment[sa]=एप्स्, एड्-ऑन् च संस्थाप्य निष्कासयन्तु
Comment[sk]=Inštalovať a odstraňovať aplikácie a doplnky
Comment[sl]=Namešča in odstranjuje aplikacije in dodatke
Comment[sv]=Installera och ta bort program och tillägg
Comment[ta]=செயலிகளையும் துணைநிரல்களையும் நிறுவி நீக்கலாம்
Comment[tr]=Uygulamalar veya eklentiler kurun veya kaldırın
Comment[uk]=Встановлення і вилучення програм і додатків
Comment[zh_CN]=安装、移除应用程序和附加组件
Comment[zh_TW]=安裝或移除應用程式與附加功能
MimeType=@DesktopMimeType@
Exec=@DesktopExec@
Icon=flufflinuxplasmadiscover
Type=Application
X-DocPath=plasma-discover/index.html
InitialPreference=5
NoDisplay=@DesktopNoDisplay@
Actions=Updates;
SingleMainWindow=true
GenericName=Software Center
GenericName[ar]=مركز البرمجيّات
GenericName[ast]=Centru de software
GenericName[az]=Proqram Təminatı Mərkəzi
GenericName[be]=Цэнтр праграмнага забеспячэння
GenericName[bg]=Софтуерен център
GenericName[ca]=Centre de programari
GenericName[ca@valencia]=Centre de programari
GenericName[cs]=Centrum softwaru
GenericName[da]=Softwarecenter
GenericName[de]=Programmverwaltung
GenericName[el]=Κέντρο λογισμικού
GenericName[en_GB]=Software Centre
GenericName[eo]=Programaro-Centro
GenericName[es]=Centro de software
GenericName[et]=Tarkvarakeskus
GenericName[eu]=Software gunea
GenericName[fa]=مرکز نرم‌افزار
GenericName[fi]=Sovellusvalikoima
GenericName[fr]=Logithèque
GenericName[gl]=Centro de programas
GenericName[he]=מרכז התוכנה
GenericName[hi]=सॉफ्टवेयर केन्द्र
GenericName[hsb]=Srjedźišćo za software
GenericName[hu]=Szoftverközpont
GenericName[ia]=Centro de Software
GenericName[id]=Pusat Perangkat Lunak
GenericName[ie]=Programmarium
GenericName[is]=Hugbúnaðarmiðstöð
GenericName[it]=Software Center
GenericName[ja]=ソフトウェアセンター
GenericName[ka]=პროგრამების ცენტრი
GenericName[ko]=소프트웨어 센터
GenericName[lt]=Programinės įrangos centras
GenericName[lv]=Programmatūras centrs
GenericName[ml]=സോഫ്റ്റ്വെയർ സെന്റർ
GenericName[my]=ဆော့ဖ်ဝဲလ်စင်တာ
GenericName[nb]=Programvaresenter
GenericName[nl]=Softwarecentrum
GenericName[nn]=Programvare­senter
GenericName[pa]=ਸਾਫਟਵੇਅਰ ਸੈਂਟਰ
GenericName[pl]=Ośrodek programów
GenericName[pt]=Centro de Aplicações
GenericName[pt_BR]=Central de aplicativos
GenericName[ro]=Centru de aplicații
GenericName[ru]=Центр программ
GenericName[sa]=तन्त्रांश् केन्द्र
GenericName[sk]=Centrum softvéru
GenericName[sl]=Programsko središče
GenericName[sr]=Софтверски центар
GenericName[sr@ijekavian]=Софтверски центар
GenericName[sr@ijekavianlatin]=Softverski centar
GenericName[sr@latin]=Softverski centar
GenericName[sv]=Programvarucentral
GenericName[ta]=மென்பொருள் மையம்
GenericName[tg]=Маркази нармафзор
GenericName[tr]=Yazılım Merkezi
GenericName[uk]=Центр програм
GenericName[zh_CN]=软件中心
GenericName[zh_TW]=軟體中心
Categories=Qt;KDE;System;
Keywords=apps;applications;flatpak;

[Desktop Action Updates]
Name=Check for app updates
Name[ar]=تحقق من تحديثات التطبيقات
Name[az]=Tətbiq yeniləmələrini yoxlayın
Name[be]=Праверыць абнаўленні праграм
Name[bg]=Проверка за актуализации на приложения
Name[ca]=Comprova si hi ha actualitzacions d'aplicacions
Name[ca@valencia]=Comprova si hi ha actualitzacions d'aplicacions
Name[cs]=Zkontrolovat aktualizace aplikací
Name[de]=Nach App-Aktualisierungen suchen
Name[el]=Έλεγχος για ενημερώσεις εφαρμογών
Name[en_GB]=Check for app updates
Name[eo]=Kontroli pri aplikaĵaj ĝisdatigoj
Name[es]=Buscar actualizaciones de aplicaciones
Name[eu]=Egiaztatu aplikazioen eguneratzeak
Name[fa]=بررسی به‌روزرسانی برنامه‌ها
Name[fi]=Tarkista sovelluspäivitykset
Name[fr]=Rechercher des mises à jour d’applications
Name[gl]=Comprobar actualizacións de aplicacións
Name[he]=בדיקת עדכוני יישומים
Name[hi]=ऐप अपडेट जाँचें
Name[hsb]=Aktualizacije nałoženjow přepruwować
Name[hu]=Alkalmazásfrissítések keresése
Name[ia]=Verificar actualisationes de applicationes
Name[id]=Periksa pembaruan aplikasi
Name[ie]=Controlar actualisamentes de applicationes
Name[is]=Athuga með forritauppfærslur
Name[it]=Controlla gli aggiornamenti delle applicazioni
Name[ja]=アプリの更新を確認
Name[ka]=აპების განახლებების შემოწმება
Name[ko]=앱 업데이트 확인
Name[lt]=Tikrinti programų atnaujinimus
Name[lv]=Pārbaudīt programmu atjauninājumus
Name[ml]=ആപ്പ് അപ്ഡേറ്റുകൾ പരിശോധിക്കുക
Name[my]=အက်ပ်အပ်ဒိတ်များကို စစ်ဆေးပါ
Name[nb]=Se etter appoppdateringer
Name[nl]=Controleren op app-updates
Name[nn]=Sjå etter appoppdateringar
Name[pa]=ਐਪ ਅੱਪਡੇਟਾਂ ਦੀ ਜਾਂਚ ਕਰੋ
Name[pl]=Sprawdź aktualizacje aplikacji
Name[pt]=Procurar atualizações de aplicações
Name[pt_BR]=Verificar atualizações de aplicativos
Name[ro]=Verifică actualizările aplicațiilor
Name[ru]=Проверить обновления приложений
Name[sa]=अनुप्रयोग-अद्यतनानि परीक्ष्यन्ताम्
Name[sk]=Skontrolovať aktualizácie aplikácií
Name[sl]=Preveri posodobitve programov
Name[sv]=Sök efter programuppdateringar
Name[ta]=செயலி புதுப்பிப்புகளைச் சரிபார்க்கவும்
Name[tr]=Uygulama güncellemelerini denetle
Name[uk]=Перевірити оновлення програм
Name[zh_CN]=检查应用更新
Name[zh_TW]=檢查應用程式更新
Icon=flufflinuxplasmadiscover
Exec=plasma-discover --mode update
